# Generated by Django 6.0.4 on 2026-04-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='occasion',
            field=models.CharField(default='Casual', max_length=50),
        ),
    ]
