# Generated by Django 6.0.4 on 2026-04-28 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_clothingitem_occasion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField(default=170.0)),
                ('weight', models.FloatField(default=65.0)),
                ('chest', models.FloatField(default=92.0)),
                ('waist', models.FloatField(default=68.0)),
                ('hips', models.FloatField(default=95.0)),
                ('shoulders', models.FloatField(default=40.0)),
                ('legs', models.FloatField(default=80.0)),
                ('skin_tone', models.CharField(default='#eeeeee', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
